Repository snc/SncRedisBundle, pull requests merged in 2018-04, with the labels that each got.

#147 IPv6 support
  DependencyInjection/Configuration/RedisDsn.php
  Tests/DependencyInjection/Configuration/RedisDsnTest.php
Labels: DX

#409 Make all bundle services private
  DependencyInjection/SncRedisExtension.php
  Resources/config/profiler_storage.xml
  Resources/config/redis.xml
  Resources/config/session.xml
Labels: dx, enhancement

#411 Add Serialization option
  DependencyInjection/Configuration/Configuration.php
  DependencyInjection/SncRedisExtension.php
  Resources/config/schema/redis-1.0.xsd
  Tests/DependencyInjection/SncRedisExtensionTest.php
Labels: feature
